#PATH
LOCAL_PROGRAM="/usr/local/"
. ~/projects/tools/setEnv.sh

#aliases
alias ls="ls --color"
alias ll="ls -lh"
alias df="df -m -h"
alias mmv="mv.sh"
alias dus="du -sh"
alias du="du -h"
alias androiddoc="firefox /usr/local/adt-bundle-linux-x86_64-20130219/sdk/docs/guide/components/index.html"
alias libgdxdoc="firefox /usr/local/adt-bundle-linux-x86_64-20130219/libgdx/docs/api/index-all.html"
alias sdcv="sdcv.sh" 
alias grep="grep --color"
alias mrm="rm_canback" 
alias eclipse=$LOCAL_PROGRAM"/eclipse/eclipse" 
alias eclipse_cpp=$LOCAL_PROGRAM"/eclipse-cpp/eclipse/eclipse" 
alias adoc="firefox /home/jinux/android-sdks/docs/guide/guide_toc.html"
alias freemind="java -jar /usr/local/jinux/resource/freemind/jar/freemind.jar &> /dev/null&" 
alias jude="java -jar /usr/local/jude/jude-community.jar &>/dev/null&"

#modify the numlock key
xmodmap -e "clear Lock" &>/dev/null
xmodmap -e "keycode 66=Escape" &>/dev/null

#close the touchpad
xinput set-prop "SynPS/2 Synaptics TouchPad" "Device Enabled" 0
#accelerate the cursor
xset mouse 20 1
export PATH=$PATH:/usr/sbin:/sbin
learn_guile_dir=/usr/local/jinux/linux_program/lisp/scheme/guile
xmodmap -e "pointer = 3 2 1"
alias minit_env="ln -s ../ourhdr.h ./ourhdr.h&&ln  -s ../stderr.c  ./stderr.c"
alias mcc="cc stderr.c"
alias info-guile="info \"Guile Reference\""
alias startMate="xinit /etc/X11/xinit/xinitrc -- /etc/X11/xinit/xserverrc"
